muesli/duf

- mounts.go
duf should only print out unexpected errors. A missing permission is not unexpected.
Calling duf with the -all flag will still list these devices, albeit with missing size / space information.
Fixes #1.
> Ignore permission errors

- README.md
- main.go
- mounts.go
- mounts_darwin.go
- mounts_linux.go
- table.go
Valid keys are: `mountpoint`, `size`, `used`, `avail`, `usage`, `inodes`, `inodes_used`, `inodes_avail`, `inodes_usage`, `type`, `filesystem`.
> Show or hide specific columns with --output

- .goreleaser.yml
A small modification to get this working in Homebrew on Linux machines.
Testing on my local Ubuntu 18.04.5 machine shows reasonable output:
```
$ goreleaser --snapshot --skip-publish --skip-sign --rm-dist
$ cat dist/duf.rb 
class Duf < Formula
desc "Disk Usage/Free Utility"
homepage "https://fribbledom.com/"
version "v0.3.1-next"
bottle :unneeded
if OS.mac?
url "https://github.com/seththeriault/duf/releases/download/v0.3.1/duf_v0.3.1-next_Darwin_x86_64.tar.gz"
sha256 "d250e5e3892c0df3e56979bbb8140a63d6d264d6e55a05e148e322aaf5b5f0b1"
elsif OS.linux?
if Hardware::CPU.intel?
url "https://github.com/seththeriault/duf/releases/download/v0.3.1/duf_v0.3.1-next_linux_x86_64.tar.gz"
sha256 "ed692006a9896a0087090d62c3f359c7b9adfa145de50f70150962d1f88d7574"
end
if Hardware::CPU.arm?
if …
```
> Update for Homebrew on Linux

- .github/workflows/build.yml
The Github Actions checkout got bumped to version 2.
Please **DO NOT MERGE** this PR until you decided on #25, since there will maybe be another checkout command where I would have to adjust the version number as well.
> Bump checkout version in build tests

- main.go
Solves #12 
Example:
```
duf --hide-fs=tmpfs,overlay
```
> Add --hide-fs to hide specific fs types

- README.md
Addresses #50 
Output:
```
$ brew tap muesli/tap; brew install duf
==> Tapping muesli/tap
Cloning into '/usr/local/Homebrew/Library/Taps/muesli/homebrew-tap'...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 24 (delta 9), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (24/24), done.
Tapped 4 formulae (49 files, 29.8KB).
==> Installing duf from muesli/tap
==> Downloading https://github.com/muesli/duf/releases/download/v0.3.1/duf_0.3.1_Darwin_x86_64.tar.gz
Already downloaded: /Users/hem/Library/Caches/Homebrew/downloads/ceb7f19f422dc77f54a8450757f8623f28d1203021fa5245614840c90f2da998--duf_0.3.1_Darwin_x86_64.tar.gz
🍺  /usr/local/Cellar/duf/0.3.1: 5 files, 2.5MB, built in 6 seconds …
```
> Fixed macOS installation instruction

- main.go
- table.go
Solves #49 
Adds `--style` flag to support terminals that can't display unicode characters, allows use of ASCII chars instead.
> Add style flag

- main.go
- mounts_darwin.go
* Remove `renderTable` error from function signature as it is always nil.
* Remove unnecessary type conversions in `mount_darwin.go`
Feel free to reject PR if you don't want it. 
I'm just struggling to find issues I can actually help out with! 😅
> Minor code improvements

- main.go
This change provides a way to enable colors (#11) via environment variable `CLICOLOR_FORCE=1`, as well as respects other env vars (described [here](https://github.com/muesli/termenv/pull/11)).
> Use EnvColorProfile

- .github/workflows/build.yml
Tests against earliest supported Go version and latest available one.
> Automatically pick go version in GitHub workflow

- filesystems_darwin.go
- filesystems_freebsd.go
- filesystems_linux.go
- filesystems_openbsd.go
- filesystems_windows.go
- groups.go
This also enables other platforms to hide certain devices per default, however currently there's only an implementation on Linux.
Calling duf with `--all` will still show hidden devices.
> Hide overlay/shm filesystems per default

- README.md
- filesystems.go
- main.go
This means you can now call `duf` with a file, dir or device path, like:
```bash
duf /home /some/file
```
Fixes #78.
> Add support for path arguments to filter output

- README.md
Now we could install `duf` via `scoop install duf` on Windows!
https://github.com/ScoopInstaller/Main/pull/1654
> README: add instructions for installing via scoop

- .goreleaser.yml
The PowerPC 64 LE is quite popular amongst researchers and enterprise users. It would be awesome if the binary is also available for this platform.
> Build binary for ppc64le architecture

- filesystems_linux.go
snap mounts like 2-3 squashfs per installed snap (once per installed
version), so you easily end up with 53 mounted squashfs, which makes
the output hard to read.
Fixes #97
> Ignore snaps by default on Linux

- filesystems_linux.go
This only shows up when launched with `--all`, but it still doesn't belong to the local devices table.
> Add FUSECTL_SUPER_MAGIC to special devices map

- .goreleaser.yml
This gives us access to the real `mountinfo`, which duf needs to correctly parse the mounted devices.
> Use a classic confinement for snap builds

- .github/workflows/lint.yml
Specifying a version is now optional in golangci-lint-action.
> Always use latest version of golangci-lint

- .github/workflows/goreleaser.yml
We need to skip this step, as it would fail for PRs, where the secret isn't available.
> Only login to snapcraft when secret is available in goreleaser workflow

- .github/workflows/goreleaser.yml
- .goreleaser.yml
- README.md
The snap package is currently unmaintained and not working correctly. The required permission for a tool like `duf` doesn't exist in snap yet, and Canonical refused turning `duf` into a classic snap, which would work around this issue. Maybe in the future.
> Remove unmaintained snap package

- go.mod
- go.sum
- main.go
After thinking about, adding the library internally would not be clean.
So I migrated it to GitHub, like proposed.
That's ok for you @muesli ?
Revision here:
https://github.com/IGLOU-EU/go-wildcard/releases/tag/v1.0.2
> Update go-wilcard lib #156

- table.go
This PR fixes #94.
Sample output screenshot:
> table: rename inode-related columns to clarify difference between bytes and inodes

- main.go
- themes.go
This theme will use the terminal's default 4-bit ANSI colors.
```bash
$ duf -theme ansi
```
Fixes #158.
> Add 'ansi' theme that uses the terminal's native 4-bit ANSI colors

- main.go
- table.go
- themes.go
Functionally zero changes to code. Runs through gofumpt linter and brings code in-line with gopls recommendations.
> run code through gofumpt and correct gopls warnings

- filesystems_linux.go
- mounts.go
deadcode has been removed from golangci-lint.
> ci: deadcode linter is no longer used

- main.go
Signed-off-by: Lancelot [1984737645@qq.com](mailto:1984737645@qq.com)
Fix the duplicate of the result list.
Fixes #190.
By using a hash table to Record the filesystem that appears, if the filesystem already exists, it doesn't append.
Before
after de-duplicated the resulting list.
> Fix the duplicate of the result list

- .goreleaser.yml
Stick to existing naming scheme (except OS references being consistently lowercase now).
> feat: migrate rest of goreleaser config
