muesli/duf

README.md, filesystems.go, main.go, mounts.go
This pull request fixes #7 
- with new option --json-output json output is rendered on the screen
- updated README.md
=> Support json output parsing via jq

README.md, go.sum, main.go, table.go
Valid sort-keys are: mountpoint, size, used, avail, usage, type, filesystem.
=> Add sorting with -size flag

mounts_darwin.go
=> Re-use Statfs_t on macOS

README.md, main.go, mounts.go, mounts_darwin.go, mounts_linux.go, table.go
=> List inode information instead of block usage with --inodes

.goreleaser.yml, README.md, filesystems_freebsd.go, mounts_freebsd.go
Help: this needs be tested before merging.
=> Add support for FreeBSD

filesystems_openbsd.go, main.go, mounts.go, mounts_darwin.go, mounts_freebsd.go, mounts_linux.go, mounts_openbsd.go
=> Add support for OpenBSD

filesystems_darwin.go, filesystems_freebsd.go, filesystems_openbsd.go
This fixes the issues mentioned in #32.
=> Detect more FreeBSD mount types

README.md
Duf is now available in termux by https://github.com/termux/termux-packages/pull/5869
=> Add Termux installation

README.md
Removes weird line breaks introduced by last PR.
=> Unbreak README list

README.md
Also groups packages a bit more logically.
=> Add FreeBSD package to README

main.go, table.go, themes.go
Solves #30
Support some sort of theme system with the flag `--theme`
Current options are `light`, `dark`
=> Add theming option

.github/workflows/build.yml, filesystems_linux.go, filesystems_windows.go, mounts.go, mounts_darwin.go, mounts_freebsd.go, mounts_linux.go, mounts_openbsd.go, mounts_windows.go
Features:
* Build & run on Windows
* Support local devices
* Support network attached devices, such as SMB
* Support Windows Sandbox devices
* Support block attributes with cluster for Windows
=> Add Windows support

.github/workflows/goreleaser.yml
This doesn't actually publish any releases, but instead checks all releases still build fine as a snapshot for each commit / PR.
=> Add goreleaser workflow

go.mod, main.go, style_unix.go, style_windows.go
Fix https://github.com/muesli/duf/issues/56#issuecomment-706274839
=> [Windows] Fix broken table structure for non-unicode code page

mounts_linux.go
=> [Linux] fix escaped type & filesystem

README.md, filesystems.go, main.go
Add only* flags to show only specified devices info
To show only individual tables:
`    duf --only-local --only-network --only-fuse --only-special --only-loops --only-binds`
To show only specific filesystems:
`    duf --only-fs tmpfs,vfat`
Close #79
=> Add only* flags to show only specified devices info

style.go, style_unix.go
=> Check rune width for all supported system to prevent broken table

mounts_windows.go
Fix #81 
Please review this pull request. @FRex
=> Feat recognize ramdisk

README.md, style.go
Install instructions & link to snapcraft.io.
=> Add snap to README

.github/workflows/goreleaser.yml, .goreleaser.yml
Build/publish snaps (along with all the other releases), with goreleaser.
=> Build snaps with goreleaser

duf.1
Hello @muesli,
I created this manpage, feel free to add it to your project. 
Best regards.
=> Add manpage

README.md
Currently in [community-testing]. I'll take this PR out of draft mode when it gets a signoff or two and I move it to [community].
=> Update Arch Linux install, in official repos now

go.mod, go.sum
Fixes a column wrapping issue.
=> Bump go-pretty to v6.2.4

main.go, table.go
Add optional availability and usage thresholds which defaults to current values. 
Closes #4
=> add availability and usage threhold option

README.md
Never hesitate to say hello :smiley:
=> Add feedback paragraph to README

go.mod, go.sum
All the improvements of termenv v0.11.0, now in a duf near you!
=> Bump termenv to v0.11.0

filesystems_darwin.go, filesystems_freebsd.go, filesystems_linux.go, filesystems_openbsd.go, filesystems_windows.go, mounts_darwin.go, mounts_freebsd.go, mounts_linux.go, mounts_openbsd.go, mounts_windows.go
=> Add Go 1.17 build tags

.github/workflows/lint-soft.yml, .golangci-soft.yml, .golangci.yml, filesystems_linux.go, groups.go, main.go, mounts.go, mounts_linux.go, table.go, themes.go
Hard-enforced linters will make the workflow fail.
=> Add separate sets of hard- and soft-enforced linters

.github/workflows/build.yml, README.md, go.mod, go.sum
=> chore: bump Go to 1.17

README.md
=> Add installation instructions for Gentoo Linux

main.go
=> Correct a typo

README.md
https://github.com/getsolus/packages/tree/2005fef4dc73882c3e39f648f460c58ee5bfc601/packages/d/duf Officially added to the Solus repo as part of the Week 38, 2023 repo updates. https://discuss.getsol.us/d/9783-sync-update-for-week-38-2023
=> Add Solus to repo packages installation instructions
